# Generated by Django 2.1.1 on 2018-12-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20181225_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Owner'), (2, 'Employee')], default=2),
        ),
    ]
