# Generated by Django 2.1.1 on 2018-10-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('USER', 'user'), ('STORE', 'store'), ('ADMIN', 'admin')], default='USER', max_length=20, verbose_name='type'),
        ),
    ]
