# Generated by Django 2.1.1 on 2019-01-01 03:17

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ranking_id',
            field=models.CharField(default=user.models.ranking_id_generator, max_length=60, unique=True, verbose_name='id'),
        ),
    ]
