# Generated by Django 2.1.1 on 2018-12-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('cost', models.IntegerField(verbose_name='cost')),
                ('damage', models.IntegerField(verbose_name='damage')),
                ('edid', models.IntegerField(verbose_name='edition id')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('flavour', models.TextField(verbose_name='flavour')),
                ('ability', models.TextField(verbose_name='ability')),
                ('ability_html', models.TextField(verbose_name='ability html')),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('empire_valid', models.DateField(verbose_name='empire valid')),
                ('release_date', models.DateField(verbose_name='release date')),
                ('image', models.URLField(verbose_name='image')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('definition', models.TextField(verbose_name='definition')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('slug', models.SlugField(verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Edition'),
        ),
        migrations.AddField(
            model_name='card',
            name='illustrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Illustrator'),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(related_name='cards', to='cards.Keyword'),
        ),
        migrations.AddField(
            model_name='card',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Kind'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.Rarity'),
        ),
    ]
